#!/usr/bin/env python
"""Reproducible demo: run the agent over the sample PDFs and write ``demo_output.md``.

This drives the same pipeline the CLI uses (load → retrieve → agent → validate) over two
documents - the (Turkish) assignment brief and an open-access (English) academic paper -
asking three questions of each, and captures the answers, sources, validation verdicts, and
reasoning traces into a single markdown log.

Run it with whatever backend is configured in the environment:

    LLM_PROVIDER=ollama OLLAMA_MODEL=qwen2.5 python examples/run_demo.py

The committed ``demo_output.md`` is the real, unedited output of one such run; re-running
regenerates it. Answers depend on the model, so they will vary between runs and backends.
"""

from __future__ import annotations

import sys
from pathlib import Path

from agentic_extraction.agent import create_agent
from agentic_extraction.config import Settings
from agentic_extraction.core.models import Chunk, ValidatedAnswer
from agentic_extraction.llm import create_llm_provider
from agentic_extraction.preprocessing import load_document
from agentic_extraction.retrieval import create_retriever
from agentic_extraction.validator import answer_with_validation, create_validator

REPO = Path(__file__).resolve().parent.parent

DEMOS = [
    {
        "title": "Assignment brief (Turkish PDF, English questions - cross-lingual)",
        "pdf": REPO / "Agentic Bilgi Çıkarımı_Ödev Çalışması.pdf",
        "questions": [
            "What are the mandatory requirements the MVP must satisfy?",
            "What questions must the architecture design document answer?",
            "What are the deliverables expected for submission?",
        ],
    },
    {
        "title": "Academic paper - Kubrak et al., 'Prescriptive process monitoring: Quo vadis?' (PeerJ CS, CC-BY)",
        "pdf": REPO / "examples" / "data" / "peerj-cs-1097.pdf",
        "questions": [
            "What problem does this paper study, and what method does it use?",
            "What framework does the paper propose to characterize the methods it reviews?",
            "What gaps or future research directions does the paper identify?",
        ],
    },
]


def _render(question: str, result: ValidatedAnswer, chunks: tuple[Chunk, ...]) -> str:
    answer = result.answer
    validation = result.validation
    chunks_by_id = {chunk.id: chunk for chunk in chunks}

    lines = [f"### Q: {question}", "", answer.answer or "_(no answer produced)_", ""]

    if answer.cited_chunk_ids:
        lines.append("**Sources:**")
        for cid in answer.cited_chunk_ids:
            chunk = chunks_by_id.get(cid)
            if chunk is None:
                lines.append(f"- `[{cid}]` (unresolved citation)")
            else:
                path = " > ".join(chunk.section_path) if chunk.section_path else "-"
                lines.append(f"- `[{cid}]` p{chunk.page} - {path}")
        lines.append("")

    lines.append(
        f"**Validation:** `{validation.verdict.value}` "
        f"(confidence {validation.confidence:.2f}, attempts {result.attempts})"
    )
    if validation.unsupported_claims:
        lines.append("")
        lines.append("Statements flagged as not grounded in the cited sources:")
        lines.extend(f"- {claim}" for claim in validation.unsupported_claims)

    lines += ["", "<details><summary>Reasoning trace</summary>", ""]
    lines.extend(f"- {step}" for step in answer.trace)
    lines += ["", "</details>", "", "---", ""]
    return "\n".join(lines)


def main() -> int:
    settings = Settings.from_env()
    out = [
        "# Demo output",
        "",
        f"Generated by `examples/run_demo.py` using the `{settings.llm_provider.value}` "
        f"backend (model `{settings.ollama_model}`). Real, unedited output.",
        "",
        "**Reading the verdicts.** `Validation` is the system's own grounding check - not a "
        "measure of whether the prose reads well. It is a strict, deterministic *lexical* "
        "test (plus an LLM critic): it certifies an answer as `grounded` only when the cited "
        "chunks' text actually contains the claims, and flags answers that paraphrase loosely, "
        "cite a chunk that does not support the claim, or answer in a different language than "
        "the source (the assignment PDF is Turkish). This is the reliability layer refusing to "
        "over-claim. Below, the framework question is certified because its citations hold up, "
        "while the method question is flagged because the model cited chunks that do not "
        "contain its (otherwise accurate) statements. A stronger backend raises the grounded "
        "rate; the value shown is the design working as intended.",
        "",
    ]

    for demo in DEMOS:
        pdf = demo["pdf"]
        print(f"== {pdf.name} ==", file=sys.stderr)
        document = load_document(str(pdf), settings)
        retriever = create_retriever(document, settings)
        llm = create_llm_provider(settings)
        validator = create_validator(settings, llm)
        agent = create_agent(document, retriever, llm, settings)

        out.append(f"## {demo['title']}")
        out.append("")
        out.append(
            f"`{pdf.name}` - {document.n_pages} pages, {len(document.chunks)} chunks, "
            f"{len(document.outline)} top-level sections."
        )
        out.append("")

        for question in demo["questions"]:
            print(f"   Q: {question}", file=sys.stderr)
            result = answer_with_validation(agent, validator, document, question)
            out.append(_render(question, result, document.chunks))

    (REPO / "examples" / "demo_output.md").write_text("\n".join(out), encoding="utf-8")
    print("wrote examples/demo_output.md", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
